from shared.exception.base import BaseAppException


class Failed(BaseAppException):
    pass
